version: '3.8'
services:
  fastapi-app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - postgres
    environment:
      DB_NAME: your_dbname
      DB_USER: your_username
      DB_PASSWORD: your_password
      DB_HOST: postgres
      restart: unless-stopped

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_dbname
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
